export interface StoreLocation {
  id: string;
  name: string;
  gmbName: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  lat: number;
  lng: number;
  googleReviewUrl: string;
  googleReviewQrCode: string;
  yelpAccount: string;
  yelpReviewUrl: string;
}

export const STORES: StoreLocation[] = [
  {
    id: "university",
    name: "Wellgreens Weed Dispensary University",
    gmbName: "Wellgreens Weed Dispensary University",
    address: "7180 University Avenue",
    city: "La Mesa",
    state: "CA",
    zip: "91942",
    lat: 32.7675,
    lng: -117.0231,
    googleReviewUrl: "https://g.page/r/Ce__U6jC-HInEBM/review",
    googleReviewQrCode: "https://drive.google.com/file/d/1EoXOqOmSqyzU6uXDIRXk0O8xklZaKjRe/view?usp=sharing",
    yelpAccount: "Wellgreens Weed Dispensary University",
    yelpReviewUrl: "https://www.yelp.com/writeareview/biz/y7_t7wv8a9VCErVhYdaf_Q",
  },
  {
    id: "vista",
    name: "Wellgreens Vista Cannabis Weed Dispensary",
    gmbName: "Wellgreens Vista Cannabis Weed Dispensary",
    address: "954 S. Santa Fe Avenue",
    city: "Vista",
    state: "CA",
    zip: "92084",
    lat: 33.2000,
    lng: -117.2425,
    googleReviewUrl: "https://g.page/r/CYBGt9waBtOsEBM/review",
    googleReviewQrCode: "https://drive.google.com/file/d/1sEclmRl0AYSh9lAOa5Fh8tbbBi3NCFLK/view?usp=sharing",
    yelpAccount: "Wellgreens Vista Cannabis Weed Dispensary",
    yelpReviewUrl: "https://www.yelp.com/writeareview/biz/oke1GbW9mUCSdqDK3-kZxg",
  },
  {
    id: "pacific-beach",
    name: "Wellgreens Pacific Beach Weed Cannabis Dispensary",
    gmbName: "Wellgreens Pacific Beach Weed Cannabis Dispensary",
    address: "4645 De Soto St.",
    city: "San Diego",
    state: "CA",
    zip: "92109",
    lat: 32.7975,
    lng: -117.2344,
    googleReviewUrl: "https://g.page/r/CbqaCiVrfWYfEBM/review",
    googleReviewQrCode: "https://drive.google.com/file/d/187DL_cBuBUO9jLFhMMkXDUkSTKiscwTP/view?usp=sharing",
    yelpAccount: "Wellgreens Pacific Beach Weed Cannabis Dispensary",
    yelpReviewUrl: "",
  },
  {
    id: "mission-valley",
    name: "Wellgreens Mission Valley Cannabis Dispensary",
    gmbName: "Wellgreens Mission Valley Cannabis Dispensary",
    address: "3703 Camino del Rio South, Unit 215-A",
    city: "San Diego",
    state: "CA",
    zip: "92108",
    lat: 32.7758,
    lng: -117.1550,
    googleReviewUrl: "https://g.page/r/CSsky8HLe60yEBM/review",
    googleReviewQrCode: "https://drive.google.com/file/d/1NQEln-Wpm8mpUwHUxhcm3Fo78CZ6_73O/view?usp=sharing",
    yelpAccount: "Wellgreens Mission Valley Cannabis Dispensary",
    yelpReviewUrl: "",
  },
  {
    id: "lemon-grove",
    name: "Wellgreens Lemon Grove Weed Dispensary",
    gmbName: "Wellgreens Lemon Grove Weed Dispensary",
    address: "6859 Federal Boulevard",
    city: "Lemon Grove",
    state: "CA",
    zip: "91945",
    lat: 32.7425,
    lng: -117.0319,
    googleReviewUrl: "https://g.page/r/Ce2H-m-pMBmOEBM/review",
    googleReviewQrCode: "https://drive.google.com/file/d/1N9HJlu6bdXuO9QmJpjr7iKsQk2QQ3YPO/view?usp=sharing",
    yelpAccount: "Wellgreens Lemon Grove Weed Dispensary",
    yelpReviewUrl: "https://www.yelp.com/writeareview/biz/Sum4GZBPABDlbYWcN_oSdQ",
  },
  {
    id: "la-mesa",
    name: "Wellgreens La Mesa Cannabis Weed Dispensary",
    gmbName: "Wellgreens La Mesa Cannabis Weed Dispensary",
    address: "5301 Lake Murray Boulevard",
    city: "La Mesa",
    state: "CA",
    zip: "91942",
    lat: 32.7678,
    lng: -117.0233,
    googleReviewUrl: "https://g.page/r/Ces3k6e5XQ-HEBM/review",
    googleReviewQrCode: "https://drive.google.com/file/d/1SQOeGG_9UAyre1ElSnOX1AEHZyogf66i/view?usp=sharing",
    yelpAccount: "Wellgreens La Mesa Cannabis Weed Dispensary",
    yelpReviewUrl: "https://www.yelp.com/writeareview/biz/Mw4XTEbCGmCid8MVLBtNXg",
  },
  {
    id: "kearny-mesa",
    name: "Wellgreens Kearny Mesa Weed Cannabis Dispensary",
    gmbName: "Wellgreens Kearny Mesa Weed Cannabis Dispensary",
    address: "8039 Balboa Ave, Suite B",
    city: "San Diego",
    state: "CA",
    zip: "92111",
    lat: 32.8219,
    lng: -117.1581,
    googleReviewUrl: "https://g.page/r/CRXHnWr_jktrEBM/review",
    googleReviewQrCode: "https://drive.google.com/file/d/1Tr0wz8WwRJbapr_pct2a3Ng_QrkWD5UR/view?usp=sharing",
    yelpAccount: "Wellgreens Kearny Mesa Weed Cannabis Dispensary",
    yelpReviewUrl: "https://www.yelp.com/writeareview/biz/2P-goT3u85o5002KbCnk1A",
  },
  {
    id: "encinitas",
    name: "Wellgreens Encinitas Weed Cannabis Dispensary",
    gmbName: "Wellgreens Encinitas Weed Cannabis Dispensary",
    address: "211 N El Camino Real",
    city: "Encinitas",
    state: "CA",
    zip: "92024",
    lat: 33.0370,
    lng: -117.2920,
    googleReviewUrl: "https://g.page/r/CV11poddg_vmEBM/review",
    googleReviewQrCode: "https://drive.google.com/file/d/1O9VWjm8vv7oTKiY9xGRpDtkIWcl7h63A/view?usp=sharing",
    yelpAccount: "Wellgreens Encinitas Weed Cannabis Dispensary",
    yelpReviewUrl: "https://www.yelp.com/writeareview/biz/rMQ_JTiP5XUpsxhW5YQg0Q",
  },
  {
    id: "city-heights",
    name: "Wellgreens City Heights Weed Cannabis Dispensary",
    gmbName: "Wellgreens City Heights Weed Cannabis Dispensary",
    address: "4337 Home Ave",
    city: "San Diego",
    state: "CA",
    zip: "92105",
    lat: 32.7481,
    lng: -117.0969,
    googleReviewUrl: "https://g.page/r/CbqPE69uFXGlEBM/review",
    googleReviewQrCode: "https://drive.google.com/file/d/1Vjsrha0FD5o9VgcsrUbJ5SCRubWBAOdx/view?usp=sharing",
    yelpAccount: "Wellgreens City Heights Weed Cannabis Dispensary",
    yelpReviewUrl: "https://www.yelp.com/writeareview/biz/H9vM_N6dhuNHH-C8S3y0",
  },
  {
    id: "chula-vista",
    name: "Wellgreens Chula Vista Weed Cannabis Dispensary",
    gmbName: "Wellgreens Chula Vista Weed Cannabis Dispensary",
    address: "1214 Broadway",
    city: "Chula Vista",
    state: "CA",
    zip: "91911",
    lat: 32.6401,
    lng: -117.0842,
    googleReviewUrl: "https://g.page/r/CTiv5mlEwfTVEBM/review",
    googleReviewQrCode: "https://drive.google.com/file/d/1E1ZXydFjc8S9Zv7K0FV1qbNG0OBGTJ66/view?usp=sharing",
    yelpAccount: "Wellgreens Chula Vista Weed Cannabis Dispensary",
    yelpReviewUrl: "https://www.yelp.com/writeareview/biz/s1p6S3hJUVijKoVi05yjuw",
  },
];
